# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-17 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
