export default {
  email: 'Email',
  password: 'Password',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  continue: 'Continue',
  username: 'Username',
  firstName: 'First Name',
  lastName: 'Last Name',
  location: 'Location',
  userApi: 'http://127.0.0.1:8000/end_user/end_user/',
  applicationJson: 'application/json',
  undefined: 'undefined',
  error: {
    userNotExist: 'ERROR! User does not exist',
    passwordWrong: 'ERROR! Password is wrong',
    noAccount: 'No account associated for user',
    incorrectPassword: 'Incorrect Password',
    genericError: 'There was an error',
    userAlreadyExists: 'User already exists',
  },
  usernameRequired: 'Username Required',
  passwordRequired: 'Password Required',
  firstNameRequired: 'First Name Required',
  lastNameRequired: 'Last Name Required',
  navigation: {
    home: 'Home',
  },
};
